### ISSUE TITLE
pip install fails on Windows

### ISSUE THREAD

**Issue by bskubi** [nvictus/pybbi#31]
Using Windows 11, pip 23.3.1, and Python 3.11.5, "pip install pybbi" fails with the following error:

> Collecting pybbi
>   Using cached pybbi-0.3.5.tar.gz (34.7 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [18 lines of output]
>       Traceback (most recent call last):
>         File "C:\Users\bskub\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "C:\Users\bskub\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\bskub\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\bskub\AppData\Local\Temp\pip-build-env-o8vwf367\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\bskub\AppData\Local\Temp\pip-build-env-o8vwf367\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\bskub\AppData\Local\Temp\pip-build-env-o8vwf367\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
>           exec(code, locals())
>         File "<string>", line 11, in <module>
>       AttributeError: module 'os' has no attribute 'uname'. Did you mean: 'name'?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
>

**Comment by bskubi** [comment]
Nevermind, I see Windows does not have a wheel.
