### ISSUE TITLE
Is this package suit for centos??when I use pip install pybbi，I met the following mistake.

### ISSUE THREAD

**Issue by hzaumsq** [nvictus/pybbi#5]
Failed building wheel for pybbi
  Running setup.py clean for pybbi
Failed to build pybbi
Installing collected packages: pybbi
  Running setup.py install for pybbi ... error
    Complete output from command /home/sqmao/miniconda2/envs/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dmcgqaoj/pybbi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-meoz7svx/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.6
    creating build/lib.linux-x86_64-3.6/bbi
    copying bbi/__init__.py -> build/lib.linux-x86_64-3.6/bbi
    running build_ext
    Compiling libkent...
    LIBRARY_PATH:
    C_INCLUDE_PATH: /home/sqmao/miniconda2/envs/python/include/openssl:
    cd src && make
    make[1]: Entering directory '/tmp/pip-install-dmcgqaoj/pybbi/src'
    gcc -g -pthread -fPIC -static -Wall -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_GNU_SOURCE -DMACHTYPE_x86_64 -L/tmp/pip-install-dmcgqaoj/pybbi/src/x86_64 -L/usr/lib -lz -lc -lpthread -I/tmp/pip-install-dmcgqaoj/pybbi/include -I/tmp/pip-install-dmcgqaoj/pybbi/src -I/usr/include -o pngwrite.o -c pngwrite.c
    pngwrite.c:7:10: 致命错误：png.h：没有那个文件或目录
     #include "png.h"   // MUST come before common.h, due to setjmp checking  in pngconf.h
              ^~~~~~~
    编译中断。
    make[1]: *** [makefile:68: pngwrite.o] Error 1
    make[1]: Leaving directory '/tmp/pip-install-dmcgqaoj/pybbi/src'
    make: *** [Makefile:32: src/x86_64/libkent.a] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dmcgqaoj/pybbi/setup.py", line 152, in <module>
        'build_ext': build_ext
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-dmcgqaoj/pybbi/setup.py", line 86, in run
        check_call(['make', 'build-c'])
      File "/home/sqmao/miniconda2/envs/python/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', 'build-c']' returned non-zero exit status 2.
    
    ----------------------------------------
Command "/home/sqmao/miniconda2/envs/python/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-dmcgqaoj/pybbi/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-meoz7svx/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-dmcgqaoj/pybbi/

**Comment by nvictus** [comment]
Not sure. Does your CentOS environment have the the pre-reqs? It looks like it might be missing libpng16.

**Comment by nvictus** [comment]
We are now distributing manylinux wheels for Python 3.5+, so I'll close this.
